routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\PromotionsController;
use App\Http\Controllers\RawMaterialsController;
use App\Http\Controllers\RawMaterialTypesController;
use App\Http\Controllers\SaleOrdersController;
use App\Http\Controllers\TablesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name("public.index");
Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('public.how-to');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::put('so/submit', [SaleOrdersController::class, 'submitOrder'])->name('sale-order.submit')->middleware(['auth']);
Route::delete('so/cancle/{so}', [SaleOrdersController::class, 'cancleOrder'])->name('sale-order.cancle')->middleware(['auth']);


Route::middleware(['auth', 'isAdmin'])->prefix('admin')->group(function () {
    Route::get('/', [HomeController::class, 'adminIndex'])->name("home.index");
    Route::get('pospos', [HomeController::class, 'pospos'])->name("home.pospos");
    Route::get('print-bill/{so}', [SaleOrdersController::class, 'printBill'])->name("print-bill");

    Route::post('promotion', [PromotionsController::class, 'store'])->name('promotion.store');
    Route::delete('promotion/{promotion}', [PromotionsController::class, 'destroy'])->name('promotion.destroy');

    Route::resource('user', UserController::class);
    Route::resource('raw-mat', RawMaterialsController::class);
    Route::resource('raw-mat-type', RawMaterialTypesController::class);
    Route::resource('prod-cate', ProductsCategoriesController::class);
    Route::resource('prod', ProductsController::class);
    Route::resource('table', TablesController::class);
    Route::get('table/{table}/toggle', [TablesController::class, 'toggleTable'])->name('table.toggle');
    Route::resource('sale-order', SaleOrdersController::class);
});


Auth::routes();

resources/views/admin/raw_mat_types/form.blade.php
@extends('layouts.admin.app')

@section('content')
    @if ($mode == 'show')
        <div class="card">
            <div class="card-header flex justify-between items-center">
                <label class="text-base align-middle">การกระทำ</label>
                <div class="flex gap-1 justify-end">
                    <a class="btn btn-info" href="{{ route('raw-mat-type.edit', ['raw_mat_type' => $model->id]) }}">
                        <i class="fas fa-edit"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th scope="row" class="font-bold text-base">ชื่อ</th>
                            <td>{{ $model->name }}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="font-bold text-base">รายละเอียด</th>
                            <td>{{ $model->detail }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    @else
        <form
            action="{{ $model->id ? route('raw-mat-type.update', ['raw_mat_type' => $model->id]) : route('raw-mat-type.store') }}"
            method="POST" class="card">
            @csrf
            @method($model->id ? 'patch': 'post')
            <div class="card-header">
                <label> ฟอร์มข้อมูล</label>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <tbody>
                        <tr class="flex">
                            <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ชื่อ</th>
                            <td class="w-full">
                                {!! Form::text('name', $model->name, ['class' => 'form-control', 'required' => true]) !!}
                            </td>
                        </tr>
                        <tr class="flex">
                            <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">รายละเอียด</th>
                            <td class="w-full">
                                {!! Form::textarea('detail', $model->detail, ['class' => 'form-control', 'required' => true]) !!}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {!! Form::submit('บันทึกข้อมูล', ['class' => 'btn btn-success btn-lg text-white']) !!}
        </form>
    @endif
@endsection

resources/views/admin/raw_mat_types/index.blade.php
@extends('layouts.admin.app')
@section('content')
    @php
    $columns = ['ชื่อ', 'รายละเอียด'];
    $attributes = ['name', 'detail'];
    $options = ['data' => $models, 'card_title' => 'ตารางหมวดหมู่วัตถุดิบ', 'create' => 'raw-mat-type.create', 'show' => 'raw-mat-type.show', 'edit' => 'raw-mat-type.edit', 'delete' => 'raw-mat-type.destroy', 'param' => 'raw_mat_type', 'columns' => $columns, 'attributes' => $attributes];
    @endphp
    @include('admin.components.table', $options)
@endsection