routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\PromotionsController;
use App\Http\Controllers\RawMaterialsController;
use App\Http\Controllers\RawMaterialTypesController;
use App\Http\Controllers\SaleOrdersController;
use App\Http\Controllers\TablesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name("public.index");
Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('public.how-to');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::put('so/submit', [SaleOrdersController::class, 'submitOrder'])->name('sale-order.submit')->middleware(['auth']);
Route::delete('so/cancle/{so}', [SaleOrdersController::class, 'cancleOrder'])->name('sale-order.cancle')->middleware(['auth']);


Route::middleware(['auth', 'isAdmin'])->prefix('admin')->group(function () {
    Route::get('/', [HomeController::class, 'adminIndex'])->name("home.index");
    Route::get('pospos', [HomeController::class, 'pospos'])->name("home.pospos");
    Route::get('print-bill/{so}', [SaleOrdersController::class, 'printBill'])->name("print-bill");

    Route::post('promotion', [PromotionsController::class, 'store'])->name('promotion.store');
    Route::delete('promotion/{promotion}', [PromotionsController::class, 'destroy'])->name('promotion.destroy');

    Route::resource('user', UserController::class);
    Route::resource('raw-mat', RawMaterialsController::class);
    Route::resource('raw-mat-type', RawMaterialTypesController::class);
    Route::resource('prod-cate', ProductsCategoriesController::class);
    Route::resource('prod', ProductsController::class);
    Route::resource('table', TablesController::class);
    Route::get('table/{table}/toggle', [TablesController::class, 'toggleTable'])->name('table.toggle');
    Route::resource('sale-order', SaleOrdersController::class);
});


Auth::routes();

app/Http/Controllers/TablesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class TablesController extends Controller
{
    public function index(Request $request)
    {
        $title = "จัดการโต๊ะ";
        $models = Tables::query();
        if ($request->search) {
            $models->where('no', 'like', "%{$request->search}%");
        }
        $models = $models->latest()->paginate($request->perPage ?? 30);
        return view('admin.table.index', compact('models', 'title'));
    }

    public function create()
    {
        $model = new Tables();
        return view('admin.table.form', ['mode' => 'create', 'model' => $model, 'title' => 'เพิ่มโต๊ะ']);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $model = Tables::create($data);
        return redirect()->route('table.show', ['table' => $model])->with('success', 'เพิ่มโต๊ะสำเร็จ');
    }

    public function show(Tables $table)
    {
        return view('admin.table.form', ['mode' => 'show', 'model' => $table, 'title' => 'ดูข้อมูล ' . $table->name]);
    }

    public function edit(Tables $table)
    {
        return view('admin.table.form', ['mode' => 'edit', 'model' => $table, 'title' => 'แก้ไขข้อมูล ' . $table->name]);
    }

    public function update(Request $request, Tables $table)
    {
        $data = $request->all();
        $table->update($data);
        return redirect()->route('table.index')->with('success', 'แก้ไขโต๊ะสำเร็จ');
    }

    public function destroy(Tables $table)
    {
        $table->delete();
        return redirect()->route('table.index')->with('success', 'ลบโต๊ะสำเร็จ');
    }

    public function toggleTable(Tables $table)
    {
        $table->active = !$table->active;
        $table->save();
        return redirect()->route('table.index')->with('success', 'บันทึกข้อมูลสำเร็จ');
    }
}

resources/views/admin/table/form.blade.php
@extends('layouts.admin.app')

@section('content')
@if ($mode == 'show')
<div class="card">
    <div class="card-header flex justify-between items-center">
        <label class="text-base align-middle">การกระทำ</label>
        <div class="flex gap-1 justify-end">
            <a class="btn btn-info" href="{{ route('table.edit', ['table' => $model->id]) }}">
                <i class="fas fa-edit"></i>
            </a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th scope="row" class="font-bold text-base">เลขโต๊ะ</th>
                    <td>{{ $model->no }}</td>
                </tr>
                <tr>
                    <th scope="row" class="font-bold text-base">ตำแหน่ง</th>
                    <td>{{ $model->row }}/{{ $model->col }}</td>
                </tr>
                <tr>
                    <th scope="row" class="font-bold text-base">เปิดใช้งาน</th>
                    <td>{{ $model->active }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@else
<form action="{{ $model->id ? route('table.update', ['table' => $model->id]) : route('table.store') }}" method="POST"
    class="card">
    @csrf
    @method($model->id ? 'patch': 'post')
    <div class="card-header">
        <label> ฟอร์มข้อมูล</label>
    </div>
    <div class="card-body">
        <table class="table table-hover">
            <tbody>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">หมายเลขโต๊ะ</th>
                    <td class="w-full">
                        {!! Form::text('name', $model->no, ['class' => 'form-control', 'required' => true]) !!}
                    </td>
                </tr>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">พิกัด</th>
                    <td class="w-full">
                        <div class="flex flex-col gap-1">
                            <div class="flex gap-1">
                                <p class="w-14 flex-grow-0">แถว</p>
                                {!! Form::number('row', $model->row, ['class' => 'form-control', 'required' => true])
                                !!}
                            </div>
                            <div class="flex gap-1">
                                <p class="w-14 flex-grow-0">คอลัมน์</p>
                                {!! Form::number('row', $model->row, ['class' => 'form-control', 'required' => true])
                                !!}
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    {!! Form::submit('บันทึกข้อมูล', ['class' => 'btn btn-success btn-lg text-white']) !!}
</form>
@endif
@endsection

resources/views/admin/table/index.blade.php
@extends('layouts.admin.app')
@section('content')

@php
$columns = ['หมายเลขโต๊ะ', 'เปิดใช้งาน'];
$attributes = ['no', 'activeText'];
$notShowAction = true;
$show_add=false;
$data = $models;
$card_title = 'ตารางหมวดหมู่โต๊ะ';
$create = 'table.create';
$show = 'table.show';
$edit = 'table.edit';
$delete = 'table.destroy';
$param = 'table';
@endphp

<div class="card">
    @if(!isset($show_add))
    <div class="flex items-center align-middle justify-between mb-2 card-header">
        <h5>{{ $card_title }}</h5>
        <a href="{{ route($create) }}" class="btn btn-success text-white">
            เพิ่ม <i class="fas fa-plus"></i>
        </a>
    </div>
    @endif
    <div class="card-body  overflow-x-auto max-w-full">
        <table class="table p-1">
            <thead class="thead-inverse">
                <tr class="text-center">
                    <th>เลขโต๊ะ</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse ($models as $model)
                <tr>
                    <td>{{ $model->no }}</td>
                    <td>
                        <div class="flex gap-2">
                            {{ $model->activeText }}
                            <form action="{{ route('table.toggle',['table'=>$model->id]) }}">
                                <button
                                    class="btn btn-{{ $model->active ? 'success': 'danger' }} text-white">คลิกเพื่อ{{ $model->active ? 'ปิด': 'เปิด' }}</button>
                            </form>
                        </div>
                    </td>
                    @if (empty($notShowAction))
                    <td>
                        <div class="flex gap-1 justify-end">
                            <a class="btn btn-info" href="{{ route($show, [$param = $model->id]) }}"><i
                                    class="fa fa-eye" aria-hidden="true"></i></a>
                            <a class="btn btn-warning" href="{{ route($edit, [$param = $model->id]) }}"><i
                                    class="fa fa-edit" aria-hidden="true"></i></a>
                            <form action="{{ route($delete, [$param = $model->id]) }}"
                                onsubmit="return confirm('คุณต้องการจะลบรายการดังกล่าวหรือไม่?')" method="POST">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger text-white"><i class="fas fa-trash"></i></button>
                            </form>
                        </div>
                    </td>
                    @endif
                </tr>
                @empty
                <tr>
                    <td colspan="{{ sizeOf($columns ?? []) + 1 }}" class="text-center p-2">
                        รายการว่างเปล่า
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        {!! $models->appends($_GET)->links() !!}
    </div>
</div>

@endsection