routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\PromotionsController;
use App\Http\Controllers\RawMaterialsController;
use App\Http\Controllers\RawMaterialTypesController;
use App\Http\Controllers\SaleOrdersController;
use App\Http\Controllers\TablesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name("public.index");
Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('public.how-to');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::put('so/submit', [SaleOrdersController::class, 'submitOrder'])->name('sale-order.submit')->middleware(['auth']);
Route::delete('so/cancle/{so}', [SaleOrdersController::class, 'cancleOrder'])->name('sale-order.cancle')->middleware(['auth']);


Route::middleware(['auth', 'isAdmin'])->prefix('admin')->group(function () {
    Route::get('/', [HomeController::class, 'adminIndex'])->name("home.index");
    Route::get('pospos', [HomeController::class, 'pospos'])->name("home.pospos");
    Route::get('print-bill/{so}', [SaleOrdersController::class, 'printBill'])->name("print-bill");

    Route::post('promotion', [PromotionsController::class, 'store'])->name('promotion.store');
    Route::delete('promotion/{promotion}', [PromotionsController::class, 'destroy'])->name('promotion.destroy');

    Route::resource('user', UserController::class);
    Route::resource('raw-mat', RawMaterialsController::class);
    Route::resource('raw-mat-type', RawMaterialTypesController::class);
    Route::resource('prod-cate', ProductsCategoriesController::class);
    Route::resource('prod', ProductsController::class);
    Route::resource('table', TablesController::class);
    Route::get('table/{table}/toggle', [TablesController::class, 'toggleTable'])->name('table.toggle');
    Route::resource('sale-order', SaleOrdersController::class);
});


Auth::routes();

app/Models/SaleOrders.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SaleOrders extends Model
{
    const STATUS_LIST = [0 => "จอง", 1 => "กำลังทาน", 2 => "ชำระเงินแล้ว", 3 => "ยกเลิก"];

    use HasFactory;

    protected $fillable = [
        'table_id',
        'amount',
        'discount',
        'appointment_at',
        'user_id',
        'status'
    ];

    protected $casts = [
        'amount' => 'int',
    ];

    public function details()
    {
        return $this->hasMany(SaleOrderDetail::class, 'sale_order_id');
    }

    public function orderTable()
    {
        return $this->belongsTo(Tables::class, 'table_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getUserNameAttribute()
    {
        return $this->user ? $this->user->name : 'ลูกค้าหน้าร้าน';
    }

    public function getTableNoAttribute()
    {
        return $this->orderTable->no;
    }

    public function getStatusNameAttribute()
    {
        return self::STATUS_LIST[$this->status];
    }
}

app/Http/Controllers/SaleOrdersController.php
<?php

namespace App\Http\Controllers;

use App\Models\SaleOrderDetail;
use App\Models\SaleOrders;
use App\Transformers\SaleOrderTrans;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class SaleOrdersController extends Controller
{
    public function index(Request $request)
    {
        $title = "จัดการสินค้า";
        $models = SaleOrders::query();
        if ($request->search) {
            $models->where('id', 'like', "%{$request->search}%");
        }

        $models = $models->latest()->paginate($request->perPage ?? 30);
        return view('admin.sale_order.index', compact('models', 'title'));
    }

    public function create()
    {
        $model = new SaleOrders();
        return view('admin.sale_order.form', ['mode' => 'create', 'model' => $model, 'title' => 'เพิ่มสินค้า']);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $model = SaleOrders::create($data);
        return redirect()->route('sale-order.show', ['sale_order' => $model])->with('success', 'เพิ่มสินค้าสำเร็จ');
    }

    public function show(SaleOrders $sale_order)
    {
        return view('admin.sale_order.form', ['mode' => 'show', 'model' => $sale_order, 'title' => 'ดูข้อมูล ' . $sale_order->name]);
    }

    public function edit(SaleOrders $sale_order)
    {
        return view('admin.sale_order.form', ['mode' => 'edit', 'model' => $sale_order, 'title' => 'แก้ไขข้อมูล ' . $sale_order->name]);
    }

    public function update(Request $request, SaleOrders $sale_order)
    {
        $data = $request->all();
        $sale_order->update($data);
        return redirect()->route('sale-order.index')->with('success', 'แก้ไขสินค้าสำเร็จ');
    }

    public function destroy(SaleOrders $sale_order)
    {
        $sale_order->delete();
        return redirect()->route('sale-order.index')->with('success', 'ลบสินค้าสำเร็จ');
    }

    public function submitOrder(Request $request)
    {
        $so = new SaleOrders();
        if ($request->saleOrderId) {
            $so = SaleOrders::where('id', $request->saleOrderId)->firstOrfail();
        } else {
            $so->table_id = $request->tableId;
        }
        switch ($request->submit) {
            case 'close':
                $so->status = 2;
                break;
            case 'open':
                $so->status = 1;
                break;
            case 'cancle':
                $so->status = 3;
            case 'save':
                $so->status = $so->status;
                break;
            default:
                $so->status = 0;
                break;
        }

        $so->amount = $request->amount;

        if (Auth::user()->role_id == 20) {
            $so->status = 0;
            $so->appointment_at = $request->appointment_at;
            $so->user_id = Auth::user()->id;
        }

        $so->save();
        // dd($request->all());
        DB::table('sale_order_details')->where('sale_order_id', $so->id)->delete();
        foreach ($request->detail as $key => $value) {
            SaleOrderDetail::create(['id' => $value['id'], 'product_id' => $value['product_id'], 'sale_order_id' => $so->id, 'quantity' => $value['quantity']]);
        }

        $request->session()->flash('success', "{$request->submit} โต๊ะ {$so->orderTable->no} สำเร็จ!");

        if ($so->status == 2) {
            $request->session()->flash('print', $so->id);
        }

        if (Auth::user()->role_id == 20) {
            return redirect()->route('public.index');
        }

        return redirect()->route('home.pospos');
    }

    public function cancleOrder(SaleOrders $so, Request $request)
    {
        $so->status = 3;
        $so->save();
        if (Auth::user()->role_id == 20) {
            $request->session()->flash('success', "ยกเลิกโต๊ะ {$so->orderTable->no} สำเร็จ!");
            return redirect()->route('public.index');
        }
    }

    public function printBill(SaleOrders $so)
    {
        $data = fractal($so, new SaleOrderTrans())->toArray()['data'];
        $pdf = PDF::loadView('pdf.bill', ['data' => $data])->setPaper([
            0, 0, 210, 280
                + sizeOf($data['details']) * 20
        ]);
        $outPut = $pdf->output();
        // return view('pdf.bill', ['data' => $data]);
        return response($outPut, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' =>  'inline; filename="' . $so->id . '.pdf"',
        ]);
    }
}

resources/views/admin/sale_order/form.blade.php
@extends('layouts.admin.app')

@section('content')
@if ($mode == 'show')
<div class="card">
    {{-- <div class="card-header flex justify-between items-center">
                <label class="text-base align-middle">การกระทำ</label>
                <div class="flex gap-1 justify-end">
                    <a class="btn btn-info" href="{{ route('sale-order.edit', ['sale_order' => $model->id]) }}">
    <i class="fas fa-edit"></i>
    </a>
</div>
</div> --}}
<div class="card-body">
    <table class="table table-hover">
        <tbody>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">รหัส</th>
                <td class="w-full">{{ $model->id }}</td>
            </tr>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">สถานะ</th>
                <td class="w-full">{{ $model->statusName }}</td>
            </tr>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">โต๊ะ</th>
                <td class="w-full">{{ $model->tableNo }}</td>
            </tr>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">รายละเอียด</th>
                <td class="w-full">
                    @forelse($model->details as $key => $value)
                    <div class="flex gap-2 justify-between">
                        <p>{{ $value->product->name }} ({{ $value->quantity }} {{ $value->product->unit }})</p>
                        <p>เป็นเงิน {{ $value->product->price * $value->quantity }} บาท</p>
                    </div>
                    <hr/>
                    @empty
                    ว่างเปล่า
                    @endforelse
                </td>
            </tr>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ราคาสุทธิ</th>
                <td class="w-full">{{ $model->amount }}</td>
            </tr>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ส่วนลด</th>
                <td class="w-full">{{ $model->discount }}</td>
            </tr>
            <tr class="flex">
                <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ลูกค้าผู้ทำรายการ</th>
                <td class="w-full">{{ $model->userName }}</td>
            </tr>
        </tbody>
    </table>
</div>
</div>
@else
<form action="{{ $model->id ? route('sale-order.update', ['sale_order' => $model->id]) : route('sale-order.store') }}"
    method="POST" class="card">
    @csrf
    @method($model->id ? 'patch': 'post')
    <div class="card-header">
        <label> ฟอร์มข้อมูล</label>
    </div>
    <div class="card-body">
        <table class="table table-hover">
            <tbody>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">รหัส</th>
                    <td class="w-full">{{ $model->id }}</td>
                </tr>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">สถานะ</th>
                    <td class="w-full">
                        {!! Form::select('status', App\Models\SaleOrders::STATUS_LIST, $model->status, ['class' =>
                        'form-select shadow-none']) !!}
                    </td>
                </tr>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">โต๊ะ</th>
                    <td class="w-full">
                        {!! Form::select('status', App\Models\Tables::get()->pluck('no', 'id'), $model->table_id,
                        ['class' => 'form-select shadow-none']) !!}
                    </td>
                </tr>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ราคาสุทธิ</th>
                    <td class="w-full">
                        {!! Form::number('amount', $model->amount, ['class' => 'form-control']) !!}
                    </td>
                </tr>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ส่วนลด</th>
                    <td class="w-full">
                        {!! Form::number('discount', $model->discount, ['class' => 'form-control']) !!}
                    </td>
                </tr>
                <tr class="flex">
                    <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ลูกค้าผู้ทำรายการ</th>
                    <td class="w-full">
                        {!! Form::select('user_id', App\Models\User::get()->pluck('name', 'id'), $model->user_id,
                        ['class' => 'form-select shadow-none']) !!}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    {!! Form::submit('บันทึกข้อมูล', ['class' => 'btn btn-success btn-lg text-white']) !!}
</form>
@endif
@endsection

resources/views/admin/sale_order/index.blade.php
@extends('layouts.admin.app')
@section('content')
    @php
    $columns = ['รหัสคำสั่งซื้อ', 'ชื่อลูกค้า', 'รวม', 'ส่วนลด', 'สถานะ'];
    $attributes = ['id', 'userName', 'amount', 'discount', 'statusName'];
    $options = ['show_add'=>false, 'data' => $models,'notEdit'=>true, 'card_title' => 'ตารางการขาย', 'create' => 'sale-order.create', 'show' => 'sale-order.show', 'edit' => 'sale-order.edit', 'delete' => 'sale-order.destroy', 'param' => 'sale_order', 'columns' => $columns, 'attributes' => $attributes];
    @endphp
    @include('admin.components.table', $options)
@endsection