routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsCategoriesController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\PromotionsController;
use App\Http\Controllers\RawMaterialsController;
use App\Http\Controllers\RawMaterialTypesController;
use App\Http\Controllers\SaleOrdersController;
use App\Http\Controllers\TablesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name("public.index");
Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('public.how-to');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::put('so/submit', [SaleOrdersController::class, 'submitOrder'])->name('sale-order.submit')->middleware(['auth']);
Route::delete('so/cancle/{so}', [SaleOrdersController::class, 'cancleOrder'])->name('sale-order.cancle')->middleware(['auth']);


Route::middleware(['auth', 'isAdmin'])->prefix('admin')->group(function () {
    Route::get('/', [HomeController::class, 'adminIndex'])->name("home.index");
    Route::get('pospos', [HomeController::class, 'pospos'])->name("home.pospos");
    Route::get('print-bill/{so}', [SaleOrdersController::class, 'printBill'])->name("print-bill");

    Route::post('promotion', [PromotionsController::class, 'store'])->name('promotion.store');
    Route::delete('promotion/{promotion}', [PromotionsController::class, 'destroy'])->name('promotion.destroy');

    Route::resource('user', UserController::class);
    Route::resource('raw-mat', RawMaterialsController::class);
    Route::resource('raw-mat-type', RawMaterialTypesController::class);
    Route::resource('prod-cate', ProductsCategoriesController::class);
    Route::resource('prod', ProductsController::class);
    Route::resource('table', TablesController::class);
    Route::get('table/{table}/toggle', [TablesController::class, 'toggleTable'])->name('table.toggle');
    Route::resource('sale-order', SaleOrdersController::class);
});


Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    const ROLE_CUSTOMER = 20;
    const ROLE_ADMIN = 30;

    const ENUM_ROLES = [20 => 'ลูกค้า', 30 => 'ผู้ดูแลระบบ'];

    protected $primaryKey = "id";
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        "id",
        'name',
        'email',
        'password',
        'role_id', 'phone'
    ];

    protected $appends = ['role'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRoleAttribute()
    {
        return $this->role_id == 20 ? 'ลูกค้า' : 'ผู้ดูแลระบบ';
    }

    public function orders()
    {
        return $this->hasMany(SaleOrders::class, 'user_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $title = "จัดการผู้ใช้งาน";
        $models = User::query();
        if ($request->search) {
            $models->where('name', 'like', "%{$request->search}%")->orWhere('email', 'like', "%{$request->search}%");
        }
        $models = $models->latest()->paginate($request->perPage ?? 30);
        return view('admin.users.index', compact('models', 'title'));
    }

    public function create()
    {
        $model = new User();
        return view('admin.users.form', ['mode' => 'create', 'model' => $model, 'title' => 'เพิ่มผู้ใช้งานระบบ']);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        if (!empty($data['password'])) {
            $data['password'] = Hash::make($data['password']);
        }
        $model = User::create($data);
        return redirect()->route('user.show', ['user' => $model])->with('success', 'เพิ่มผู้ใช้งานสำเร็จ');
    }

    public function show(User $user)
    {
        return view('admin.users.form', ['mode' => 'show', 'model' => $user, 'title' => 'ดูข้อมูล ' . $user->name]);
    }

    public function edit(User $user)
    {
        return view('admin.users.form', ['mode' => 'edit', 'model' => $user, 'title' => 'แก้ไขข้อมูล ' . $user->name]);
    }

    public function update(Request $request, User $user)
    {
        $data = $request->all();
        if (!empty($data['password'])) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }
        $user->update($data);
        return redirect()->route('user.index')->with('success', 'แก้ไขผู้ใช้งานสำเร็จ');
    }

    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('user.index')->with('success', 'ลบผู้ใช้งานสำเร็จ');
    }
}

resources/views/admin/users/form.blade.php
@extends('layouts.admin.app')

@section('content')
    @if ($mode == 'show')
        <div class="card">
            <div class="card-header flex justify-between items-center">
                <label class="text-base align-middle">การกระทำ</label>
                <div class="flex gap-1 justify-end">
                    <a class="btn btn-info" href="{{ route('user.edit', ['user' => $model->id]) }}"><i
                            class="fas fa-edit    "></i></a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th scope="row" class="font-bold text-base">ชื่อ</th>
                            <td>{{ $model->name }}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="font-bold text-base">อีเมล์</th>
                            <td>{{ $model->email }}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="font-bold text-base">บทบาท</th>
                            <td>{{ $model->role }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    @else
        <form action="{{ $model->id ? route('user.update', ['user' => $model->id]) : route('user.store') }}" method="POST"
            class="card">
            @csrf
            @method($model->id ? 'patch': 'post')
            <div class="card-header">
                <label> ฟอร์มข้อมูล</label>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <tbody>
                        <tr class="flex">
                            <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">ชื่อ</th>
                            <td class="w-full">
                                {!! Form::text('name', $model->name, ['class' => 'form-control', 'required' => true]) !!}
                            </td>
                        </tr>
                        <tr class="flex">
                            <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">อีเมล์</th>
                            <td class="w-full">
                                {!! Form::text('email', $model->email, ['class' => 'form-control', 'required' => true]) !!}
                            </td>
                        </tr>
                        <tr class="flex">
                            <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">รหัสผ่าน</th>
                            <td class="w-full">
                                {!! Form::text('password', null, ['class' => 'form-control', 'placeholder' => $model->id ? 'ใส่รหัสผ่านใหม่หากต้องการแก้ไข' : 'ใส่รหัสผ่าน', 'required' => empty($model->id)]) !!}
                            </td>
                        </tr>
                        <tr class="flex">
                            <th scope="row" class="font-bold text-base w-1/3 md:w-1/4">บทบาท</th>
                            <td class="w-full">
                                {!! Form::select('role_id', App\Models\User::ENUM_ROLES, $model->role_id, ['class' => 'form-control']) !!}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {!! Form::submit('บันทึกข้อมูล', ['class' => 'btn btn-success btn-lg text-white']) !!}
        </form>
    @endif
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin.app')
@section('content')
    @php
    $columns = ['ชื่อ', 'อีเมล์', 'บทบาท'];
    $attributes = ['name', 'email', 'role'];
    $options = ['data' => $models, 'card_title' => 'ตารางผู้ใช้', 'create' => 'user.create', 'show' => 'user.show', 'edit' => 'user.edit', 'delete' => 'user.destroy', 'param' => 'user', 'columns' => $columns, 'attributes' => $attributes];
    @endphp
    @include('admin.components.table', $options)
@endsection